import { Inter } from "next/font/google";
import "./globals.css";
import ReactqProvider from "./reactq";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "C-Food&Frozen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReactqProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ReactqProvider>
  );
}
