import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import "./globals.css";
import ReactqProvider from "./reactq";

import SessionProvider from "./components/SessionProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "C-Food&Frozen",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <SessionProvider session={session}>
      <ReactqProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </ReactqProvider>
    </SessionProvider>
  );
}
